site_name: AshLog
site_description: AshLog documentation

repo_url: https://github.com/ashlog-rest/docs/
edit_uri: ./edit/main/docs

theme:
  name: readthedocs

nav:
  - 'index.md'
  - REST API:
    - 'rest-api/setup.md'
    - 'rest-api/endpoint.md'
    - 'rest-api/actions.md'
  - Web Dashboard:
    - 'web-dashboard.md'